name: Advocate Schema Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, live]
    paths: 
      - 'advocates/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Setup .NET 8
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: |
        cd validation
        dotnet restore
        
    - name: Run
      run: |
        cd validation
        dotnet run -c Release
