name: Advocate Schema Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, live]
    paths: 
      - 'advocates/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup .NET 8
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: |
        cd validation
        dotnet restore
        
    - name: Run
      run: |
        cd validation
        dotnet run -c Release
